### PR TITLE
Ensure /users/:id endpoint only lists private devices when the requesting user is authorized to see them

### PR DESCRIPTION
**Pull request by timcowlishaw**
If the current authenticated user is the user being requested, they are visible
If the current authenticated user is an admin, they are visible
If there is no current user, or the current user is a different citizen or researcher, they are not.

### CODE REVIEW

**Comment by timcowlishaw** [comment]
Hey @oscgonfer FYI I've added a commit to ensure that user tags and location are properly listed for devices on the user endpoint (this simplifies things too to just reuse the /devices representation as much as possible rather than using a completely different serialisation.

**Comment by oscgonfer** [comment]
Much nicer, thank you for also reusing the device representation. This approach makes it cleaner and more maintainable. It makes me think of the health check (that we have in the list for the future) and how we can try to reuse devices to make more informative views in the different front-end views (i.e. if one day we add the health to the device, I'd like that to propagate  to the different views of the devices adapted obviously to each context, without having to rewrite it all each time).

As far as this one, I'll try to test in staging once I have time and merge if all goes well.

**Comment by timcowlishaw** [comment]
Yeah, i think that might be something to put on a general 'tech debt'
refactoring list for when we have the kits stuff shipped - try and settle
on a 'default representation' in JSON for each model type and reuse it
across all the endpoints - there's a lot of duplication in those jbuilder
files!

In fact, I might create a tech debt issue now with a list.

**Comment by oscgonfer** [comment]
That sounds great! Thank you so much

**Comment by oscgonfer** [comment]
> Hey @oscgonfer FYI I've added a commit to ensure that user tags and location are properly listed for devices on the user endpoint (this simplifies things too to just reuse the /devices representation as much as possible rather than using a completely different serialisation.

Hi @timcowlishaw 

I was just checking this on staging and I see that we now return the `user_tags` on the `/users` devices endpoint. **However** I see the `location` is not. I believe is due to `/location` being in `/devices` data in the `/device` endpoint.

Users I am comparing: https://api.smartcitizen.me/v0/users/148/ and https://staging-api.smartcitizen.me/v0/users/148/

Device I am using: https://staging-api.smartcitizen.me/v0/devices/15618/

**Comment by timcowlishaw** [comment]
aha good spot, thanks Oscar - that's now fixed!

**Pull request merged**
