### PR TITLE
Docker compose upgrade

### PR DESCRIPTION
**Pull request by oscgonfer**
This branch is to add changes on the docker-compose example file, in particular to make use of resource limitations and better restart policies of services.

Bear in mind that there is no more version at the beginning of the file, or there shouldn't be.

#235

### CODE REVIEW

**Comment by oscgonfer** [comment]
hi @timcowlishaw any idea why this may fail?

**Comment by timcowlishaw** [comment]
We should also look into a better way of handling host-specific docker-compose config - one option would be to have a checked-in `docker-compose.example.yml` and ignore docker-compose.yml itself (then update the github actions and readme to make it  clear this needs to be copied), or maybe there's something in https://docs.docker.com/compose/multiple-compose-files/ we could use to copy out host-specific stuff into includes?

**Review by timcowlishaw — APPROVED** [review]
Hey Oscar! This is looking good to me - I've fixed a small syntax error in the new compose file, and also:

1) renamed to `compose.yml`, the new default
2) added a `compose.override.local.yml` for local development
3) expanded the local dev section in the readme to make it clear what this is for
4) consistently renamed `docker-compose` to `docker compose` everywhere to reflect the new recommended systax

**Comment by timcowlishaw** [comment]
Oh, i've also just split out the compose.yml file into an include for each service, which should make things more manageable!

**Comment by oscgonfer** [comment]
@timcowlishaw Is it OK for me to merge and we document on a separate issue?

**Comment by timcowlishaw** [comment]
Hey @oscgonfer ! Aha sure thing, that sounds sensible - i can get to the documentation part later this week!

**Pull request merged**
